services:
  # Service PHP
  php:
    build: .
    container_name: ecoride-php
    ports:
      - "8000:80"
    restart: unless-stopped
    depends_on:
      - db
      - mongo
    env_file:
      - ./.env
    volumes:
      - ./src:/var/www/html/src
      - ./public:/var/www/html/public

  # Database MySQL
  db:
    image: mysql:8.0
    container_name: ecoride-db
    restart: always
    ports:
      - "3307:3306"
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: Europe/Paris
    volumes:
      - db_data:/var/lib/mysql
      - ./database/ecoride.sql:/docker-entrypoint-initdb.d/01-ecoride.sql:ro

    #Service de visualisation de la base de données
  adminer:
    image: adminer
    container_name: ecoride-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db

  # Database MongoDB
  mongo:
    image: mongo:6
    container_name: ecoride-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      TZ: Europe/Paris
    volumes:
      - mongo_data:/data/db
      - ./database:/tmp/database

  #Service de visualisation de la base de données MongoDB
  mongo-express:
    image: mongo-express:latest
    container_name: ecoride-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_DATABASE: ${MONGO_DB}
      ME_CONFIG_MONGODB_USERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_PASSWORD: ${MONGO_PASS}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASS}

volumes:
  db_data:
  mongo_data:
